export const Acolyte = {
	name: "Acolyte",
	tier: 1,
	totalJP: 54,
	allocatedJP: 0,
	availableJP: 54,
	preRequisite: null,
	skillTree: {
		Angelus: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Angelus",
			PreRequisites: [
				{
					RepelEvil: 3,
				},
			],
		},
		AquaBenedicta: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Aqua Benedicta",
			PreRequisites: [],
		},
		Blessing: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Blessing",
			PreRequisites: [
				{
					RepelEvil: 5,
				},
			],
		},
		Cure: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Cure",
			PreRequisites: [
				{
					Heal: 2,
				},
			],
		},
		DecreaseAGI: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Decrease AGI",
			PreRequisites: [
				{
					IncreaseAGI: 1,
				},
			],
		},
		Heal: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Heal",
			PreRequisites: [],
		},
		HolyLight: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 5,
			Name: "Holy Light",
			PreRequisites: [],
		},
		IncreaseAGI: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Increase AGI",
			PreRequisites: [
				{
					Heal: 3,
				},
			],
		},
		IncreaseSPRecovery: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Increase SP Recovery",
			PreRequisites: [],
		},
		MaceMastery: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Mace Mastery",
			PreRequisites: [],
		},
		Pneuma: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Pneuma",
			PreRequisites: [
				{
					Teleport: 2,
				},
			],
		},
		RepelEvil: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Repel Evil",
			PreRequisites: [],
		},
		Ruwach: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Ruwach",
			PreRequisites: [],
		},
		SignumCrucis: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 5,
			Name: "Signum Crucis",
			PreRequisites: [],
		},
		Teleport: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 2,
			Name: "Teleport",
			PreRequisites: [
				{
					Ruwach: 1,
				},
			],
		},
	},
};
