export default Acolyte = {
	Angelus: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 10,
		Name: "",
		PreRequisites: [
			{
				RepelEvil: 3,
			},
		],
	},
	AquaBenedicta: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	Blessing: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 10,
		Name: "",
		PreRequisites: [
			{
				RepelEvil: 5,
			},
		],
	},
	Cure: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [
			{
				Heal: 2,
			},
		],
	},
	DecreaseAgility: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 10,
		Name: "",
		PreRequisites: [
			{
				IncreaseAgility: 1,
			},
		],
	},
	Heal: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 10,
		Name: "",
		PreRequisites: [],
	},
	HolyLight: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 5,
		Name: "",
		PreRequisites: [],
	},
	IncreaseAgility: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 10,
		Name: "",
		PreRequisites: [
			{
				Heal: 3,
			},
		],
	},
	IncreaseSpRecovery: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 10,
		Name: "",
		PreRequisites: [],
	},
	MaceMastery: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 10,
		Name: "",
		PreRequisites: [],
	},
	Pneuma: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [
			{
				Teleport: 2,
			},
		],
	},
	RepelEvil: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 10,
		Name: "",
		PreRequisites: [],
	},
	Ruwach: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	SignumCrucis: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 5,
		Name: "",
		PreRequisites: [],
	},
	Teleport: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 2,
		Name: "",
		PreRequisites: [
			{
				Ruwach: 1,
			},
		],
	},
};
