export const Merchant = {
	totalJP: 54,
	preRequisites: "Novice",
	skillTree: {
		AxeMastery: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "",
			PreRequisites: [],
		},
		CartRevolution: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "",
			PreRequisites: [],
		},
		CurseTomahawk: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 5,
			Name: "",
			PreRequisites: [],
		},
		Efficiency: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 5,
			Name: "",
			PreRequisites: [],
		},
		EnlargeWeightLimit: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "",
			PreRequisites: [],
		},
		FindingOre: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "",
			PreRequisites: [],
		},
		ItemAppraisal: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "",
			PreRequisites: [],
		},
		Mammonite: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "",
			PreRequisites: [],
		},
		PushcartMastery: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 5,
			Name: "",
			PreRequisites: [],
		},
	},
};
