export const Novice = {
	name: "Novice",
	tier: 0,
	totalJP: 9,
	preRequisite: null,
	skillTree: {
		BasicSkill: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Basic Skill",
			PreRequisites: [],
		},
		CallMount: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Call Mount",
			PreRequisites: [],
		},
		ChangeCart: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Change Cart",
			PreRequisites: [],
		},
		ItemFinding: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Item Finding",
			PreRequisites: [],
		},
		MonsterMemory: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Monster Memory",
			PreRequisites: [],
		},
		PickUp: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Pick Up",
			PreRequisites: [],
		},
		Pushcart: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Pushcart",
			PreRequisites: [],
		},
		Sense: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Sense",
			PreRequisites: [],
		},
		Vending: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Vending",
			PreRequisites: [],
		},
	},
};
