export default Novice = {
	BasicSkill: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	CallMount: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	ChangeCart: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	ItemFinding: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	MonsterMemory: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	PickUp: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	Pushcart: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	Sense: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
	Vending: {
		AdditionalInfo: "",
		Description: "",
		Form: "",
		FormulaInfo: "",
		MaxLv: 1,
		Name: "",
		PreRequisites: [],
	},
};
