export const Merchant = {
	name: "Merchant",
	tier: 1,
	totalJP: 54,
	allocatedJP: 0,
	availableJP: 54,
	preRequisite: null,
	skillTree: {
		AxeMastery: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Axe Mastery",
			PreRequisites: [],
		},
		CartRevolution: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Cart Revolution",
			PreRequisites: [],
		},
		CursedTomahawk: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 5,
			Name: "Cursed Tomahawk",
			PreRequisites: [],
		},
		Efficiency: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 5,
			Name: "Efficiency",
			PreRequisites: [],
		},
		EnlargeWeightLimit: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Enlarge Weight Limit",
			PreRequisites: [],
		},
		FindingOre: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Finding Ore",
			PreRequisites: [],
		},
		ItemAppraisal: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 1,
			Name: "Item Appraisal",
			PreRequisites: [],
		},
		Mammonite: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 10,
			Name: "Mammonite",
			PreRequisites: [],
		},
		PushcartMastery: {
			AdditionalInfo: "",
			Description: "",
			Form: "",
			FormulaInfo: "",
			MaxLv: 5,
			Name: "Pushcart Mastery",
			PreRequisites: [],
		},
	},
};
